export const userData = [
  {
    forename: "Juan",
    surname: "Pérez",
    email: "juan.perez@example.com",
    password: "password123",
    role: "admin",
  },
  {
    forename: "María",
    surname: "López",
    email: "maria.lopez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Carlos",
    surname: "Sánchez",
    email: "carlos.sanchez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Ana",
    surname: "González",
    email: "ana.gonzalez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Luis",
    surname: "Ramírez",
    email: "luis.ramirez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Laura",
    surname: "Martínez",
    email: "laura.martinez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Pedro",
    surname: "Fernández",
    email: "pedro.fernandez@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Sofía",
    surname: "Torres",
    email: "sofia.torres@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Jorge",
    surname: "Herrera",
    email: "jorge.herrera@example.com",
    password: "password123",
    role: "user",
  },
  {
    forename: "Carmen",
    surname: "Vega",
    email: "carmen.vega@example.com",
    password: "password123",
    role: "user",
  },
];
